"""
SkyNet-RWA-Nexus Governance Simulation.

Demonstrates L4 Data Fabric capabilities:
1. Federated Learning with Differential Privacy.
2. Data Provenance Tracing for Regulatory Compliance.
"""

import numpy as np
from nexus_core.data_fabric import (
    DataLineageGraph, LineageNode, NodeType, EdgeType,
    FederatedClient, FederatedServer
)

def run_governance_demo():
    print(">>> [SkyNet Governance] Initializing Data Fabric...\n")
    
    # 1. Federated Learning Session
    server = FederatedServer()
    client_a = FederatedClient("Operator-A", epsilon=0.5) # High privacy
    client_b = FederatedClient("Operator-B", epsilon=2.0) # Low privacy
    
    print("[FedAI] Starting Training Round 1...")
    
    # Simulating private local data (e.g., congestion levels)
    data_a = [0.8, 0.9, 0.7] 
    data_b = [0.2, 0.1, 0.3]
    
    w_global = server.global_weights
    
    # Clients compute private updates
    update_a = client_a.train_round(w_global, data_a)
    update_b = client_b.train_round(w_global, data_b)
    
    # Server aggregates
    new_global = server.aggregate([update_a, update_b])
    
    print(f"[FedAI] Global Model Updated. Mean Weight: {np.mean(new_global):.4f}")
    print(f"[FedAI] Privacy Preserved (Noise Injected). Raw updates hidden.\n")

    # 2. Data Lineage Recording
    print("[Lineage] Recording Asset Provenance...")
    dlg = DataLineageGraph()
    
    # Nodes
    node_model = LineageNode("Model-v1.0", NodeType.ENTITY, "CongestionPredictor")
    node_training = LineageNode("Training-Run-101", NodeType.ACTIVITY, "FedAvg-Round-1")
    node_op_a = LineageNode("Operator-A", NodeType.AGENT, "SkyHigh Ops")
    node_op_b = LineageNode("Operator-B", NodeType.AGENT, "Urban Wings")
    
    dlg.add_node(node_model)
    dlg.add_node(node_training)
    dlg.add_node(node_op_a)
    dlg.add_node(node_op_b)
    
    # Edges
    # Model was generated by Training
    dlg.add_edge(node_model.id, node_training.id, EdgeType.WAS_GENERATED_BY)
    # Training was attributed to Operators
    dlg.add_edge(node_training.id, node_op_a.id, EdgeType.WAS_ATTRIBUTED_TO)
    dlg.add_edge(node_training.id, node_op_b.id, EdgeType.WAS_ATTRIBUTED_TO)
    
    print("[Lineage] Graph Built: Entity -> Activity -> Agents")

    # 3. Regulatory Audit
    print("\n>>> [Regulator] Auditing Model-v1.0...")
    
    # Trace back
    trace = dlg.trace_back("Model-v1.0")
    print(f"[Audit] Trace Path: {[n.id for n in trace]}")
    
    is_trusted = dlg.verify_provenance("Model-v1.0", "Operator-A")
    if is_trusted:
        print("[Audit] COMPLIANT: Asset verified to originate from Trusted Operator-A.")
    else:
        print("[Audit] VIOLATION: Origin unknown.")

if __name__ == "__main__":
    run_governance_demo()

