import React, { useState, useEffect } from 'react';
import { Aircraft, InsuranceClaim, Route, RWAToken } from '../types';
import { AIRCRAFT, ROUTES, INSURANCE_CLAIMS } from '../services/mockData';
import { playTextToSpeech } from '../services/geminiService';
import { smartContractService } from '../services/smartContractService';
import MapVisualization from '../components/MapVisualization';
import { Activity, Battery, Power, Volume2, Bell, ShieldAlert, FileText, Coins, Camera, Wallet, Plus, Loader2, Briefcase, TrendingUp, TrendingDown, ExternalLink, CheckCircle, AlertCircle, Wifi, Fuel, Percent, Map as MapIcon, Signal, ChevronDown, ChevronUp, Home } from 'lucide-react';

interface OperatorAppProps {
  onBackToHome: () => void;
}

const OperatorApp: React.FC<OperatorAppProps> = ({ onBackToHome }) => {
  const [myAircraft, setMyAircraft] = useState<Aircraft[]>(AIRCRAFT.filter(a => a.operator === 'SkyHigh Ops'));
  const [isOnline, setIsOnline] = useState(true);
  const [activeTab, setActiveTab] = useState<'fleet' | 'risk' | 'finance'>('fleet');
  const [claims, setClaims] = useState<InsuranceClaim[]>(INSURANCE_CLAIMS);
  
  // Tokenization State
  const [isMinting, setIsMinting] = useState(false);
  const [mintingStep, setMintingStep] = useState('');
  const [selectedAssetId, setSelectedAssetId] = useState<string>('');
  const [tokenSymbol, setTokenSymbol] = useState('');
  const [isSymbolAutoGenerated, setIsSymbolAutoGenerated] = useState(false);
  const [valuation, setValuation] = useState(10000);
  const [issuedTokens, setIssuedTokens] = useState<RWAToken[]>([]);
  const [expandedTokenId, setExpandedTokenId] = useState<string | null>(null);
  const [projectedApy, setProjectedApy] = useState<string>('—');

  // Real-time Telemetry Simulation
  useEffect(() => {
    const telemetryInterval = setInterval(() => {
      setMyAircraft(prevAircraft => prevAircraft.map(ac => {
         // Create a copy to update
         let updated = { ...ac };
         const time = Date.now();

         if (ac.status === 'BUSY') {
             // Simulate active flight dynamics
             // 1. Speed fluctuation (Cruising speed ~130-160 km/h)
             // Add sine wave oscillation for more realistic data curves
             const baseSpeed = 145;
             const speedOscillation = 10 * Math.sin(time / 2000);
             const speedNoise = (Math.random() * 4) - 2;
             updated.speed = Math.floor(baseSpeed + speedOscillation + speedNoise);

             // 2. Altitude fluctuation (Cruising alt ~300-500m)
             const baseAlt = 450;
             const altOscillation = 20 * Math.cos(time / 3000);
             const altNoise = (Math.random() * 6) - 3;
             updated.altitude = Math.floor(baseAlt + altOscillation + altNoise);

             // 3. Battery drain (Fast drain when busy)
             updated.batteryLevel = parseFloat(Math.max(0, ac.batteryLevel - 0.02).toFixed(2));

             // 4. Coordinates (Simulate flight path)
             const timeSec = time / 5000;
             const offset = (parseInt(ac.id.replace(/\D/g, '')) || 0) * 10;
             
             // Vary flight patterns based on ID to look less uniform on map
             if (ac.id.includes('01')) {
                 // Wide Circle
                 updated.currentLocation = {
                     x: 50 + (25 * Math.cos(timeSec + offset)),
                     y: 50 + (25 * Math.sin(timeSec + offset))
                 };
             } else if (ac.id.includes('02')) {
                 // Figure 8 Pattern
                 updated.currentLocation = {
                     x: 50 + (30 * Math.cos(timeSec + offset)),
                     y: 50 + (15 * Math.sin(2 * (timeSec + offset)))
                 };
             } else {
                 // Ellipse
                 updated.currentLocation = {
                     x: 50 + (20 * Math.cos(timeSec + offset)),
                     y: 50 + (30 * Math.sin(timeSec + offset))
                 };
             }

         } else if (ac.status === 'AVAILABLE') {
             // Stationary but active (Hovering/Idling)
             updated.speed = 0;
             updated.altitude = 0;
             // Slow battery drain (standby)
             updated.batteryLevel = parseFloat(Math.max(0, ac.batteryLevel - 0.005).toFixed(2));
         } else if (ac.status === 'OFFLINE') {
             // Recharging simulation
             updated.speed = 0;
             updated.altitude = 0;
             updated.batteryLevel = parseFloat(Math.min(100, ac.batteryLevel + 0.5).toFixed(2));
         }

         return updated;
      }));
    }, 500); // 500ms update rate for smoother map animation

    return () => clearInterval(telemetryInterval);
  }, []);

  // Update projected APY and suggest symbol when asset changes
  useEffect(() => {
    if (selectedAssetId) {
        // Simulate analyzing the asset's historical revenue
        setProjectedApy((5 + Math.random() * 7).toFixed(2) + '%');
        
        // Auto-suggest symbol based on asset details
        const asset = [...AIRCRAFT, ...ROUTES].find(a => a.id === selectedAssetId);
        if (asset) {
            let suggestion = '';
            if ('regNumber' in asset) {
                // Aircraft: Use part of Reg Number + RWA suffix
                // e.g. UAM-NY-02 -> NY02-RWA
                const parts = asset.regNumber.split('-');
                suggestion = `${parts[1] || 'UAM'}${parts[2] || '01'}-RWA`;
            } else {
                // Route: Use Initials + IX
                suggestion = asset.name.split(' ').map(n => n[0]).join('') + '-IX';
            }
            
            // Only set if user hasn't typed a custom one yet or if it was auto-generated previously
            if (!tokenSymbol || isSymbolAutoGenerated) {
                setTokenSymbol(suggestion.toUpperCase());
                setIsSymbolAutoGenerated(true);
            }
        }
    } else {
        setProjectedApy('—');
        // Only clear if we are in an auto-generated state or empty
        if (isSymbolAutoGenerated || !tokenSymbol) {
            setTokenSymbol('');
            setIsSymbolAutoGenerated(false);
        }
    }
  }, [selectedAssetId]);

  // Simulation of revenue events
  useEffect(() => {
    const loadTokens = async () => {
        const allTokens = await smartContractService.getAllTokens();
        // Filter for current operator (Mock ID: SkyHigh Ops)
        setIssuedTokens(allTokens.filter(t => t.issuerId === 'SkyHigh Ops'));
        return allTokens;
    };
    loadTokens();
    
    // Poll for price updates and simulate revenue events
    const interval = setInterval(async () => {
        const currentTokens = await loadTokens();
        
        // Simulate random revenue event for a TOKENIZED asset (creates dynamic market movement)
        // Only simulate if we have tokens to simulate on
        if (currentTokens.length > 0 && Math.random() > 0.6) {
            // Pick a random token from the global list to simulate activity
            const randomToken = currentTokens[Math.floor(Math.random() * currentTokens.length)];
            const revenueAmount = 50 + Math.random() * 250;
            
            // Trigger smart contract update
            // This simulates "Other" revenue sources besides direct citizen bookings (e.g. cargo, government contracts)
            await smartContractService.recordAssetRevenue(randomToken.assetId, revenueAmount);
        }
    }, 5000);
    return () => clearInterval(interval);
  }, [isMinting]); 

  const toggleStatus = (id: string) => {
    setMyAircraft(prev => prev.map(ac => {
      if (ac.id === id) {
        const newStatus = ac.status === 'OFFLINE' ? 'AVAILABLE' : 'OFFLINE';
        playTextToSpeech(`${ac.regNumber} is now ${newStatus.toLowerCase()}`);
        return { ...ac, status: newStatus };
      }
      return ac;
    }));
  };

  const handleSymbolChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTokenSymbol(e.target.value.toUpperCase());
    setIsSymbolAutoGenerated(false); // User manually took control
  };

  const handleMintToken = async () => {
    if(!selectedAssetId || !tokenSymbol) return;
    
    // Validation
    if (!/^[A-Z0-9-]+$/.test(tokenSymbol)) {
        setMintingStep('Error: Invalid Symbol format');
        playTextToSpeech("Invalid token symbol. Use only uppercase letters, numbers, and hyphens.");
        return;
    }
    
    if (valuation <= 0 || isNaN(valuation)) {
        setMintingStep('Error: Valuation must be positive');
        playTextToSpeech("Please enter a valid valuation amount.");
        return;
    }
    
    const asset = [...AIRCRAFT, ...ROUTES].find(a => a.id === selectedAssetId);
    if(!asset) return;

    setIsMinting(true);
    setMintingStep('Initializing Smart Contract...');
    playTextToSpeech(`Initiating smart contract deployment for ${tokenSymbol}. Broadcasting to testnet.`);

    try {
      // Step 1: Compile & Deploy
      await new Promise(r => setTimeout(r, 800));
      setMintingStep('Compiling Asset Metadata...');
      
      await smartContractService.deployAssetToken(
        asset as Aircraft | Route,
        valuation,
        tokenSymbol,
        'SkyHigh Ops'
      );
      
      // Step 2: Verify (Simulated)
      setMintingStep('Verifying Block Confirmation...');
      await new Promise(r => setTimeout(r, 1500));
      
      setMintingStep('Linking Revenue Stream Oracle...');
      await new Promise(r => setTimeout(r, 800));

      setMintingStep('Success!');
      playTextToSpeech("Block confirmed. Asset successfully tokenized. Trading is now live.");
      
      // Trigger explicit refresh of local token list immediately
      const allTokens = await smartContractService.getAllTokens();
      setIssuedTokens(allTokens.filter(t => t.issuerId === 'SkyHigh Ops'));
      
      // Reset Form
      await new Promise(r => setTimeout(r, 1000)); // Short delay so they see Success
      setTokenSymbol('');
      setValuation(10000);
      setSelectedAssetId('');
      setIsSymbolAutoGenerated(false);
      setMintingStep('');
      
    } catch (e: any) {
      console.error(e);
      setMintingStep(`Error: ${e.message}`);
      playTextToSpeech("Deployment failed. Please check transaction parameters.");
      await new Promise(r => setTimeout(r, 3000)); // Show error for 3s
      setMintingStep('');
    } finally {
      setIsMinting(false);
    }
  };

  const getAssetDetails = (assetId: string) => {
    // Check local state first for real-time status updates
    const localAc = myAircraft.find(a => a.id === assetId);
    if (localAc) return { 
        type: 'Aircraft', 
        name: localAc.regNumber, 
        desc: localAc.model, 
        status: localAc.status,
        metric: `${localAc.batteryLevel}% Battery | ${localAc.speed || 0} km/h`
    };

    const ac = AIRCRAFT.find(a => a.id === assetId);
    if (ac) return { 
        type: 'Aircraft', 
        name: ac.regNumber, 
        desc: ac.model, 
        status: ac.status,
        metric: `${ac.batteryLevel}% Battery | ${ac.speed || 0} km/h`
    };
    
    const rt = ROUTES.find(r => r.id === assetId);
    if (rt) return { 
        type: 'Route', 
        name: rt.name, 
        desc: `${rt.distanceKm}km | ${rt.startPoint} -> ${rt.endPoint}`, 
        status: 'ACTIVE',
        metric: `${rt.durationMinutes} min avg duration`
    };
    
    return { type: 'Unknown', name: 'Unknown Asset', desc: '', status: 'N/A', metric: 'N/A' };
  };

  // Filter available assets (not yet tokenized)
  const tokenizedAssetIds = new Set(issuedTokens.map(t => t.assetId));
  const availableRoutes = ROUTES.filter(r => !tokenizedAssetIds.has(r.id));
  const availableAircraft = myAircraft.filter(a => !tokenizedAssetIds.has(a.id));

  const totalRevenue = 12450.00;
  const flightsToday = 8;

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 font-sans flex flex-col">
      {/* Sidebar / Nav (Mobile Simplified) */}
      <nav className="bg-slate-800 border-b border-slate-700 p-4 flex justify-between items-center sticky top-0 z-10">
        <div className="flex items-center gap-2">
           <button 
             onClick={onBackToHome} 
             className="p-2 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white mr-2 transition-colors"
             title="Return Home"
           >
             <Home size={20} />
           </button>
           <div className="w-8 h-8 bg-indigo-500 rounded-lg flex items-center justify-center font-bold">OP</div>
           <div>
             <h1 className="font-bold leading-tight">SkyHigh Ops</h1>
             <div className="flex items-center gap-1.5">
                <span className={`w-2 h-2 rounded-full ${isOnline ? 'bg-green-500' : 'bg-red-500'}`}></span>
                <span className="text-xs text-slate-400">{isOnline ? 'System Online' : 'System Offline'}</span>
             </div>
           </div>
        </div>
        <div className="flex gap-3 items-center">
            <button 
              onClick={() => setActiveTab('fleet')}
              className={`px-3 py-1 rounded text-sm ${activeTab === 'fleet' ? 'bg-slate-700 text-white' : 'text-slate-400'}`}
            >
              Fleet
            </button>
            <button 
              onClick={() => setActiveTab('risk')}
              className={`px-3 py-1 rounded text-sm ${activeTab === 'risk' ? 'bg-slate-700 text-white' : 'text-slate-400'}`}
            >
              Risk
            </button>
             <button 
              onClick={() => setActiveTab('finance')}
              className={`px-3 py-1 rounded text-sm ${activeTab === 'finance' ? 'bg-slate-700 text-white' : 'text-slate-400'}`}
            >
              Finance
            </button>
            <div className="h-6 w-px bg-slate-600 mx-2"></div>
            <button className="p-2 bg-slate-700 rounded-full hover:bg-slate-600 relative">
                <Bell size={18} />
                <span className="absolute top-0 right-0 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-slate-700"></span>
            </button>
        </div>
      </nav>

      <main className="p-4 max-w-5xl mx-auto space-y-6 w-full flex-1">
        
        {/* Stats Row */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-slate-800 p-4 rounded-xl border border-slate-700">
                <p className="text-slate-400 text-xs uppercase tracking-wider mb-1">Today's Revenue</p>
                <p className="text-2xl font-bold text-green-400">${(totalRevenue / 30).toFixed(2)}</p>
            </div>
            <div className="bg-slate-800 p-4 rounded-xl border border-slate-700">
                <p className="text-slate-400 text-xs uppercase tracking-wider mb-1">Active Flights</p>
                <p className="text-2xl font-bold text-blue-400">{flightsToday}</p>
            </div>
            <div className="bg-slate-800 p-4 rounded-xl border border-slate-700 col-span-2 bg-gradient-to-r from-indigo-900 to-slate-800">
                <p className="text-indigo-200 text-xs uppercase tracking-wider mb-1">Tokenized Asset Value (RWA)</p>
                <div className="flex justify-between items-end">
                    <p className="text-2xl font-bold text-white">{issuedTokens.length > 0 ? issuedTokens.reduce((acc, t) => acc + (t.price * t.totalSupply), 0).toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }) : '$0'}</p>
                    <span className="text-xs text-indigo-300 bg-indigo-900/50 px-2 py-1 rounded border border-indigo-700/50">Yield: 8.5% APY Avg</span>
                </div>
            </div>
        </div>

        {activeTab === 'fleet' && (
          <div className="space-y-6">
            {/* Real-time Tracking Map */}
            <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden">
                 <div className="p-4 border-b border-slate-700 flex justify-between items-center bg-slate-900/50">
                    <h2 className="text-lg font-semibold flex items-center gap-2">
                        <MapIcon size={20} className="text-blue-400"/> Live Fleet Tracking
                    </h2>
                    <div className="flex items-center gap-3">
                        <div className="flex items-center gap-2 bg-slate-900 px-3 py-1.5 rounded-full border border-slate-700/50">
                            <Signal size={14} className="text-green-400 animate-pulse" />
                            <span className="text-xs text-slate-400">Status: <span className="text-green-400 font-mono font-bold">CONNECTED</span></span>
                        </div>
                        <div className="text-[10px] text-slate-500 font-mono border-l border-slate-700 pl-3">
                             <span className="block">LATENCY: 24ms</span>
                             <span className="block">SOURCE: SIMULATED</span>
                        </div>
                    </div>
                 </div>
                 <div className="h-72 w-full relative">
                    <MapVisualization 
                        routes={ROUTES} 
                        aircraft={myAircraft} 
                        className="h-full w-full" 
                    />
                    {/* Overlay Legend */}
                    <div className="absolute bottom-2 right-2 bg-slate-900/90 backdrop-blur px-3 py-2 rounded border border-slate-700 text-xs space-y-1">
                        <div className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-blue-500"></span> Active</div>
                        <div className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-500"></span> Available</div>
                        <div className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-slate-500"></span> Offline</div>
                    </div>
                 </div>
            </div>

            {/* Fleet Cards */}
            <div>
                <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                    <Activity size={20} className="text-indigo-400"/> Telemetry & Control
                </h2>
                <div className="grid gap-4 md:grid-cols-2">
                    {myAircraft.map(ac => (
                        <div key={ac.id} className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden group hover:border-slate-600 transition-all">
                            <div className="relative h-32 bg-slate-900">
                                {/* Simulated Cockpit View Preview */}
                                {ac.videoFeedUrl && (
                                    <img src={ac.videoFeedUrl} className="w-full h-full object-cover opacity-50 group-hover:opacity-80 transition-opacity" alt="Cockpit" />
                                )}
                                <div className="absolute top-2 right-2 bg-black/60 backdrop-blur px-2 py-1 rounded text-xs text-white flex items-center gap-1">
                                    <Camera size={12} /> CAM-01
                                </div>
                                {/* Live Telemetry HUD */}
                                <div className="absolute bottom-2 left-2 right-2 flex justify-between text-[10px] text-white font-mono">
                                    <div className="bg-black/50 px-2 py-1 rounded backdrop-blur border border-white/10 flex items-center gap-1">
                                        <span className="text-slate-400">ALT:</span> {ac.altitude || 0}m
                                    </div>
                                    <div className="bg-black/50 px-2 py-1 rounded backdrop-blur border border-white/10 flex items-center gap-1">
                                        <span className="text-slate-400">SPD:</span> {ac.speed || 0}km/h
                                    </div>
                                    <div className="bg-black/50 px-2 py-1 rounded backdrop-blur border border-white/10 flex items-center gap-1">
                                        <span className="text-slate-400">LOC:</span> {ac.currentLocation.x.toFixed(1)}, {ac.currentLocation.y.toFixed(1)}
                                    </div>
                                </div>
                            </div>
                            <div className="p-4 flex justify-between items-start">
                                <div>
                                    <div className="flex items-center gap-2 mb-1">
                                        <h3 className="font-bold text-lg">{ac.regNumber}</h3>
                                        <span className={`px-2 py-0.5 text-[10px] rounded-full font-bold uppercase tracking-wide border ${
                                            ac.status === 'AVAILABLE' ? 'bg-green-900/30 text-green-400 border-green-800' :
                                            ac.status === 'BUSY' ? 'bg-blue-900/30 text-blue-400 border-blue-800' :
                                            ac.status === 'MAINTENANCE' ? 'bg-yellow-900/30 text-yellow-400 border-yellow-800' :
                                            ac.status === 'EMERGENCY' ? 'bg-red-900/30 text-red-400 border-red-800' :
                                            'bg-slate-700 text-slate-400 border-slate-600'
                                        }`}>
                                            {ac.status}
                                        </span>
                                    </div>
                                    <p className="text-sm text-slate-400">{ac.model}</p>
                                </div>
                                <div className="flex flex-col items-end gap-2">
                                    <div className="flex items-center gap-1.5 text-sm text-slate-300">
                                        <Battery size={16} className={ac.batteryLevel < 20 ? 'text-red-400' : 'text-green-400'} />
                                        {ac.batteryLevel}%
                                    </div>
                                </div>
                            </div>
                            
                            {/* Controls */}
                            <div className="bg-slate-900/50 p-3 border-t border-slate-700 flex justify-between items-center">
                                <div className="text-xs text-slate-500">Last maintenance: 2 days ago</div>
                                <div className="flex gap-2">
                                    <button 
                                        onClick={() => toggleStatus(ac.id)}
                                        className="p-2 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white transition-colors"
                                        title="Toggle Power"
                                    >
                                        <Power size={18} />
                                    </button>
                                    <button 
                                        onClick={() => playTextToSpeech(`Status report for ${ac.regNumber}. Battery at ${ac.batteryLevel} percent. Systems nominal.`)}
                                        className="p-2 hover:bg-slate-700 rounded-lg text-slate-400 hover:text-white transition-colors"
                                        title="Audio Report"
                                    >
                                        <Volume2 size={18} />
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Recent Jobs */}
            <div>
                <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                     Mission Log
                </h2>
                <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden">
                     <table className="w-full text-sm text-left">
                        <thead className="bg-slate-900/50 text-slate-400 border-b border-slate-700">
                            <tr>
                                <th className="p-4 font-medium">Route</th>
                                <th className="p-4 font-medium">Aircraft</th>
                                <th className="p-4 font-medium text-right">Income</th>
                                <th className="p-4 font-medium text-right">Status</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-700">
                            {[1, 2, 3].map(i => (
                                <tr key={i} className="hover:bg-slate-700/50 transition-colors">
                                    <td className="p-4">{ROUTES[i-1]?.name || 'Custom Charter'}</td>
                                    <td className="p-4 font-mono text-slate-300">{AIRCRAFT[i-1]?.regNumber}</td>
                                    <td className="p-4 text-right font-mono text-green-400">+$120.00</td>
                                    <td className="p-4 text-right">
                                        <span className="text-xs bg-green-900/30 text-green-400 border border-green-800 px-2 py-1 rounded">Completed</span>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                     </table>
                </div>
            </div>
          </div>
        )}

        {activeTab === 'risk' && (
          <div className="space-y-6">
             {/* Risk Scoreboard */}
             <div className="bg-slate-800 p-6 rounded-xl border border-slate-700">
                 <div className="flex items-center justify-between mb-4">
                    <h2 className="text-lg font-semibold flex items-center gap-2">
                        <ShieldAlert className="text-orange-400" /> Operational Risk Score
                    </h2>
                    <span className="text-3xl font-bold text-green-400">94/100</span>
                 </div>
                 <div className="w-full bg-slate-700 h-2 rounded-full overflow-hidden">
                     <div className="bg-green-500 h-full w-[94%]"></div>
                 </div>
                 <p className="text-slate-400 text-sm mt-2">Low risk profile. Insurance premiums reduced by 12%.</p>
             </div>

             {/* Insurance Claims */}
             <div>
                <div className="flex justify-between items-center mb-4">
                    <h2 className="text-lg font-semibold flex items-center gap-2">
                        <FileText className="text-indigo-400" /> Insurance Claims
                    </h2>
                    <button className="text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-2 rounded font-medium transition-colors">
                        + New Claim
                    </button>
                </div>
                
                <div className="space-y-3">
                    {claims.map(claim => (
                        <div key={claim.id} className="bg-slate-800 p-4 rounded-xl border border-slate-700 flex justify-between items-center">
                            <div>
                                <div className="flex items-center gap-2 mb-1">
                                    <span className="font-mono text-slate-300">{claim.id}</span>
                                    <span className={`text-[10px] px-2 py-0.5 rounded uppercase font-bold ${
                                        claim.status === 'APPROVED' ? 'bg-green-900/30 text-green-400' : 'bg-yellow-900/30 text-yellow-400'
                                    }`}>
                                        {claim.status}
                                    </span>
                                </div>
                                <p className="text-sm text-slate-400">{claim.description}</p>
                            </div>
                            <div className="text-right">
                                <p className="font-bold text-white">${claim.amount}</p>
                                <p className="text-xs text-slate-500">{new Date(claim.incidentDate).toLocaleDateString()}</p>
                            </div>
                        </div>
                    ))}
                </div>
             </div>
          </div>
        )}

        {activeTab === 'finance' && (
          <div className="space-y-6">
             {/* Issuance Dashboard */}
             <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden">
                 <div className="p-6 border-b border-slate-700 flex justify-between items-center">
                     <div>
                         <h2 className="text-lg font-semibold flex items-center gap-2">
                            <Wallet className="text-blue-400" /> Asset Tokenization
                         </h2>
                         <p className="text-slate-400 text-sm mt-1">
                           Issue RWA tokens backed by your fleet's revenue. Raise capital by selling fractional ownership of your routes.
                         </p>
                     </div>
                     <div className="hidden md:flex items-center gap-2 bg-slate-900 px-3 py-1.5 rounded border border-slate-600/50">
                         <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                         <span className="text-xs text-slate-400 font-mono">Connected: Polygon Testnet</span>
                     </div>
                 </div>
                 
                 <div className="p-6 grid md:grid-cols-2 gap-8">
                     {/* Left Column: Configuration Form */}
                     <div className="space-y-4">
                        <div>
                          <label className="block text-sm text-slate-400 mb-1">Select Asset to Tokenize</label>
                          <select 
                            className="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 outline-none disabled:opacity-50"
                            value={selectedAssetId}
                            onChange={(e) => setSelectedAssetId(e.target.value)}
                            disabled={isMinting}
                          >
                             <option value="">-- Select Available Asset --</option>
                             {availableRoutes.length > 0 && (
                                 <optgroup label="Routes">
                                    {availableRoutes.map(r => <option key={r.id} value={r.id}>{r.name} (Route)</option>)}
                                 </optgroup>
                             )}
                             {availableAircraft.length > 0 && (
                                 <optgroup label="Aircraft">
                                    {availableAircraft.map(a => <option key={a.id} value={a.id}>{a.regNumber} - {a.model}</option>)}
                                 </optgroup>
                             )}
                             {availableRoutes.length === 0 && availableAircraft.length === 0 && (
                                 <option disabled>All assets already tokenized</option>
                             )}
                          </select>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm text-slate-400 mb-1">Est. APY</label>
                                <div className="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 text-slate-300 font-mono flex items-center justify-between">
                                    <span>{projectedApy}</span>
                                    <Percent size={14} className="text-green-500"/>
                                </div>
                            </div>
                             <div>
                                <label className="block text-sm text-slate-400 mb-1">Est. Gas Fee</label>
                                <div className="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 text-slate-300 font-mono flex items-center justify-between">
                                    <span>0.004 ETH</span>
                                    <Fuel size={14} className="text-orange-500"/>
                                </div>
                            </div>
                        </div>

                        <div>
                          <label className="block text-sm text-slate-400 mb-1">Token Symbol (Ticker)</label>
                          <input 
                            type="text" 
                            className="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 outline-none uppercase font-mono disabled:opacity-50"
                            placeholder="e.g. NY01-RWA"
                            value={tokenSymbol}
                            onChange={handleSymbolChange}
                            maxLength={12}
                            disabled={isMinting}
                          />
                        </div>

                        <div>
                          <label className="block text-sm text-slate-400 mb-1">Total Valuation ($)</label>
                          <input 
                            type="number" 
                            className="w-full bg-slate-900 border border-slate-600 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 outline-none disabled:opacity-50"
                            value={valuation}
                            onChange={(e) => {
                                const val = parseInt(e.target.value);
                                setValuation(isNaN(val) ? 0 : val);
                            }}
                            min={1000}
                            placeholder="10000"
                            disabled={isMinting}
                          />
                          <p className="text-xs text-slate-500 mt-1">1 Token = $1.00 at issuance. Total Supply = {valuation ? valuation.toLocaleString() : 0}</p>
                        </div>

                        <div className="pt-2">
                            <button 
                              onClick={handleMintToken}
                              disabled={isMinting || !selectedAssetId || !tokenSymbol || valuation <= 0}
                              className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-slate-700 disabled:text-slate-500 text-white py-3 rounded-lg font-semibold flex items-center justify-center gap-2 transition-all shadow-lg shadow-blue-900/20 disabled:shadow-none"
                            >
                               {isMinting ? <Loader2 className="animate-spin" /> : <><Plus size={18} /> Deploy Smart Contract</>}
                            </button>
                            {mintingStep && (
                                <div className={`text-center mt-3 text-xs font-mono animate-pulse ${mintingStep.startsWith('Error') ? 'text-red-400' : 'text-blue-400'}`}>
                                    {mintingStep}
                                </div>
                            )}
                        </div>
                     </div>

                     {/* Right Column: Token Preview & Education */}
                     <div className="bg-slate-900/50 p-6 rounded-xl border border-slate-700 flex flex-col justify-center">
                        <h3 className="text-sm font-semibold text-slate-400 mb-4 uppercase tracking-wider flex items-center gap-2">
                           <Coins size={14} /> Token Preview
                        </h3>
                        
                        {/* Live Preview Card */}
                        <div className="bg-slate-900 border border-blue-500/30 rounded-xl p-4 shadow-lg relative overflow-hidden group hover:border-blue-500/50 transition-all">
                            <div className="absolute top-0 right-0 bg-blue-600 text-white text-[10px] px-2 py-1 rounded-bl font-bold tracking-wide shadow-lg">
                                DRAFT
                            </div>
                            <div className="flex justify-between items-start mb-3">
                                <div className="flex items-center gap-3">
                                    <div className="w-10 h-10 rounded bg-gradient-to-br from-indigo-900 to-slate-800 border border-slate-700 text-indigo-300 flex items-center justify-center font-bold text-sm shadow-inner">
                                        {tokenSymbol ? tokenSymbol.substring(0, 3) : '...'}
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-sm text-white">{selectedAssetId ? getAssetDetails(selectedAssetId).name : 'Select Asset...'}</h3>
                                        <p className="text-[10px] text-slate-400 font-mono tracking-tight">
                                            {tokenSymbol || 'SYMBOL'} • {selectedAssetId ? getAssetDetails(selectedAssetId).type : 'Type'}
                                        </p>
                                    </div>
                                </div>
                            </div>
                            
                            <div className="mt-4 space-y-3">
                                <div className="flex justify-between text-xs text-slate-400 border-b border-slate-800 pb-2">
                                    <span>Market Cap</span>
                                    <span className="text-slate-200 font-mono">${valuation.toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between text-xs text-slate-400">
                                    <span>Projected Yield</span>
                                    <span className="text-green-400 font-bold font-mono">{projectedApy}</span>
                                </div>
                            </div>
                        </div>

                        <div className="mt-6 text-center">
                             {availableAircraft.length === 0 && availableRoutes.length === 0 ? (
                                 <div className="p-3 bg-yellow-900/20 border border-yellow-700/50 rounded text-xs text-yellow-500 flex items-center justify-center gap-2">
                                     <AlertCircle size={14} /> All assets tokenized
                                 </div>
                             ) : (
                                 <p className="text-xs text-slate-500">
                                    This token will be minted on the Polygon network and available for citizen investment immediately.
                                 </p>
                             )}
                        </div>
                     </div>
                 </div>
             </div>

             {/* Issued Assets List */}
             <div className="bg-slate-800 rounded-xl border border-slate-700 overflow-hidden">
                <div className="p-6 border-b border-slate-700 flex justify-between items-center">
                    <h2 className="text-lg font-semibold flex items-center gap-2">
                        <Briefcase className="text-indigo-400" /> Issued Assets Portfolio
                    </h2>
                    <span className="text-xs bg-slate-700 px-2 py-1 rounded text-slate-300">{issuedTokens.length} Assets Active</span>
                </div>
                <div className="p-6">
                    {issuedTokens.length === 0 ? (
                        <div className="text-center py-8 text-slate-500">
                            No assets tokenized yet. Use the form above to issue your first RWA token.
                        </div>
                    ) : (
                        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                            {issuedTokens.map(token => {
                                const assetDetails = getAssetDetails(token.assetId);
                                const isExpanded = expandedTokenId === token.id;
                                const soldPct = ((token.totalSupply - token.availableSupply) / token.totalSupply) * 100;
                                const currentMarketCap = (token.price * token.totalSupply).toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });

                                return (
                                    <div 
                                        key={token.id} 
                                        className={`bg-slate-900 border rounded-xl transition-all cursor-pointer hover:shadow-lg ${isExpanded ? 'border-blue-500 col-span-full md:col-span-2 bg-slate-900/80' : 'border-slate-700 hover:border-slate-500 hover:bg-slate-800'}`}
                                        onClick={() => setExpandedTokenId(isExpanded ? null : token.id)}
                                    >
                                        <div className="p-4">
                                            <div className="flex justify-between items-start mb-3">
                                                <div className="flex items-center gap-3">
                                                    <div className="w-10 h-10 rounded-lg bg-indigo-900/50 text-indigo-300 border border-indigo-500/20 flex items-center justify-center font-bold text-sm shadow-inner">
                                                        {token.symbol.substring(0, 3)}
                                                    </div>
                                                    <div>
                                                        <h3 className="font-bold text-sm text-slate-100">{token.name}</h3>
                                                        <div className="flex items-center gap-2 text-[10px] text-slate-400">
                                                             <span className="bg-slate-800 px-1.5 py-0.5 rounded border border-slate-700">{token.symbol}</span>
                                                             <span>{assetDetails.type}</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="flex items-start gap-3">
                                                    <div className="text-right">
                                                        <p className="font-bold text-sm text-slate-100">${token.price.toFixed(2)}</p>
                                                        <p className={`text-[10px] flex items-center justify-end ${token.change24h >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                                                            {token.change24h >= 0 ? <TrendingUp size={10} className="mr-1"/> : <TrendingDown size={10} className="mr-1"/>}
                                                            {Math.abs(token.change24h)}%
                                                        </p>
                                                    </div>
                                                    <div className={`text-slate-500 transition-transform duration-300 ${isExpanded ? 'rotate-180' : ''}`}>
                                                        <ChevronDown size={18} />
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="mt-4 space-y-3">
                                                <div className="flex justify-between text-xs text-slate-400 border-b border-slate-800/50 pb-2">
                                                    <span>Market Cap</span>
                                                    <span className="text-slate-200 font-mono">{currentMarketCap}</span>
                                                </div>
                                                <div className="flex justify-between text-xs text-slate-400">
                                                    <span>Current Yield (APY)</span>
                                                    <span className="text-green-400 font-bold font-mono">{token.yieldApy.toFixed(2)}%</span>
                                                </div>
                                                
                                                <div className="pt-2">
                                                    <div className="flex justify-between text-[10px] text-slate-500 mb-1">
                                                        <span>Distribution: {soldPct.toFixed(1)}%</span>
                                                        <span>{token.totalSupply.toLocaleString()} Total</span>
                                                    </div>
                                                    <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
                                                        <div className="bg-blue-500 h-full rounded-full" style={{ width: `${soldPct}%` }}></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        {/* Expanded Asset Details */}
                                        {isExpanded && (
                                            <div className="bg-slate-950/50 border-t border-slate-800 p-4 animate-in fade-in slide-in-from-top-2 duration-200 rounded-b-xl">
                                                <h4 className="text-xs font-bold text-slate-400 uppercase mb-3 flex items-center gap-2 tracking-wider">
                                                    <Activity size={12} /> Underlying Real-World Asset Data
                                                </h4>
                                                <div className="grid grid-cols-2 gap-4 text-sm">
                                                    <div className="bg-slate-900/50 p-3 rounded border border-slate-800">
                                                        <p className="text-slate-500 text-[10px] uppercase tracking-wider mb-1">Asset Name</p>
                                                        <p className="font-medium text-slate-200">{assetDetails.name}</p>
                                                    </div>
                                                    <div className="bg-slate-900/50 p-3 rounded border border-slate-800">
                                                        <p className="text-slate-500 text-[10px] uppercase tracking-wider mb-1">Operational Status</p>
                                                        <span className={`inline-block px-2 py-0.5 rounded text-[10px] mt-0.5 font-bold border ${
                                                            assetDetails.status === 'ACTIVE' || assetDetails.status === 'AVAILABLE' || assetDetails.status === 'BUSY' 
                                                            ? 'bg-green-900/20 text-green-400 border-green-900/30' 
                                                            : 'bg-slate-800 text-slate-400 border-slate-700'
                                                        }`}>
                                                            {assetDetails.status}
                                                        </span>
                                                    </div>
                                                    
                                                    {token.contractAddress && (
                                                        <div className="col-span-2 bg-slate-900/50 p-3 rounded border border-slate-800">
                                                            <p className="text-slate-500 text-[10px] uppercase tracking-wider mb-1">Smart Contract Address</p>
                                                            <div className="flex items-center justify-between group/addr cursor-pointer">
                                                                <p className="text-xs font-mono text-blue-400 truncate w-full group-hover/addr:text-blue-300 transition-colors">{token.contractAddress}</p>
                                                                <CheckCircle size={12} className="text-blue-500 opacity-0 group-hover/addr:opacity-100 transition-opacity" />
                                                            </div>
                                                        </div>
                                                    )}

                                                    <div className="bg-slate-900/50 p-3 rounded border border-slate-800">
                                                        <p className="text-slate-500 text-[10px] uppercase tracking-wider mb-1">Live Telemetry</p>
                                                        <p className="text-slate-300 text-xs font-mono flex items-center gap-1">
                                                            <Signal size={10} className={assetDetails.status === 'OFFLINE' ? 'text-slate-600' : 'text-green-500 animate-pulse'} />
                                                            {assetDetails.metric}
                                                        </p>
                                                    </div>
                                                    <div className="bg-slate-900/50 p-3 rounded border border-slate-800">
                                                        <p className="text-slate-500 text-[10px] uppercase tracking-wider mb-1">Holders</p>
                                                        <p className="text-slate-300 text-xs font-mono">{token.ownerCount || 1} Wallets</p>
                                                    </div>
                                                    
                                                    <div className="col-span-2 bg-slate-900/50 p-3 rounded border border-slate-800">
                                                        <p className="text-slate-500 text-[10px] uppercase tracking-wider mb-1">Asset Description</p>
                                                        <p className="text-slate-400 text-xs leading-relaxed">{assetDetails.desc}</p>
                                                    </div>
                                                </div>
                                                <div className="mt-4 pt-3 border-t border-slate-800 flex justify-between items-center">
                                                    <span className="text-[10px] text-slate-600">Deployed: {token.deploymentDate ? new Date(token.deploymentDate).toLocaleDateString() : 'N/A'}</span>
                                                    <button className="text-xs flex items-center gap-1 text-indigo-400 hover:text-indigo-300 transition-colors bg-indigo-900/20 px-3 py-1.5 rounded border border-indigo-500/20 hover:border-indigo-500/40">
                                                        View on PolygonScan <ExternalLink size={12} />
                                                    </button>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>
             </div>
          </div>
        )}

      </main>
    </div>
  );
};

export default OperatorApp;